set_property PACKAGE_PIN T18 [get_ports B1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports B1[0]]
set_property PACKAGE_PIN W19 [get_ports B1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports B1[1]]
set_property PACKAGE_PIN T17 [get_ports B1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports B1[2]]
set_property PACKAGE_PIN U17 [get_ports B1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports B1[3]]

set_property PACKAGE_PIN R2 [get_ports B2[0]]
set_property IOSTANDARD LVCMOS33 [get_ports B2[0]]
set_property PACKAGE_PIN T1 [get_ports B2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports B2[1]]
set_property PACKAGE_PIN U1 [get_ports B2[2]]
set_property IOSTANDARD LVCMOS33 [get_ports B2[2]]
set_property PACKAGE_PIN W2 [get_ports B2[3]]
set_property IOSTANDARD LVCMOS33 [get_ports B2[3]]


set_property PACKAGE_PIN U18 [get_ports push]
set_property IOSTANDARD LVCMOS33 [get_ports push]

set_property PACKAGE_PIN W7 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]
set_property PACKAGE_PIN W6 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN U8 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN V8 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN U5 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN V5 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN U7 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
set_property PACKAGE_PIN V7 [get_ports seg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[7]]

set_property PACKAGE_PIN W5 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]


set_property PACKAGE_PIN U2 [get_ports Anode_Activate[0]]                    
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[0]]
set_property PACKAGE_PIN U4 [get_ports Anode_Activate[1]]                    
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[1]]
set_property PACKAGE_PIN V4 [get_ports Anode_Activate[2]]               
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[2]]
set_property PACKAGE_PIN W4 [get_ports Anode_Activate[3]]          
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate[3]]